version: '3'

services:
    postgresqldb:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=fullzer4
            - POSTGRES_DB=SAEP
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "16543:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "gabrielpelizzaro@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"